language: php

dist: trusty
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

git:
    depth: 1

cache:
    apt: true
    timeout: 691200
    directories:
        - vendor
        - $HOME/.composer/cache

env:
  global:
    - PATH="$PATH:~/bin"
    - PHALCON_VERSION="v3.1.2"

before_install:
    - phpenv config-rm xdebug.ini || true
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - travis_retry composer install --quiet --no-interaction --no-ansi --no-progress --optimize-autoloader --dev --prefer-dist --no-suggest --ignore-platform-reqs
    - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}

install:
    - (cd cphalcon/build; bash install &>/dev/null)
    - phpenv config-add cphalcon/tests/_ci/phalcon.ini

script:
  - vendor/bin/phpcs

notifications:
    email:
        recipients:
            - build@phalconphp.com
        on_success: change
        on_failure: always
